language: c
addons:
  apt:
    packages:
    - cmake
    - curl
    - libboost-test-dev
sudo: false
dist: trusty

env:
   global:
   - "LD_LIBRARY_PATH='usr/lib' LIBRARY_PATH='usr/lib'"

script:
- mktemp
- echo ~
- cmake --version
- ./travis-ci.sh
