language: [c, c++]
addons:
  apt:
    packages:
    - cmake
    - curl
    - libsodium-dev
sudo: required
env:
   global:
   - "LD_LIBRARY_PATH='usr/lib' LIBRARY_PATH='usr/lib'"

script:
- ./travis-ci.sh
