os: 'Visual Studio 2015'

init:
  - 'git config --global core.autocrlf input'

environment:
  matrix:
    - platform: x64
      configuration: Release
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x86
      configuration: Debug

before_build:
  - >-
    cmake . -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=C:\Projects\libs
    "-DCMAKE_BUILD_TYPE=%CONFIGURATION%" -DBOOST_ROOT=C:\Libraries\boost_1_63_0
    "-DSLIPROCK_TRACE=%CONFIGURATION%"

build:
  project: INSTALL.vcxproj

before_test:
  - ps: |
      $config = ${Env:Configuration}
      if ($config -eq 'Release') {
        $limit = 100
      } else {
        $limit = 3
      }
      Write-Host $path
      for ($i = 0; $i -lt $limit; $i++) {
        Write-Host "Run number $i"
        cmd /c /k "src\${config}\mytest.exe 2>&1"
      }

notifications:
  - provider: Email
    to:
      - demiobenour@gmail.com
