os: 'Visual Studio 2015'

init:
  - 'git config --global core.autocrlf input'

environment:
  matrix:
    - platform: x64
      configuration: Release
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x86
      configuration: Debug

before_build:
  - >-
    cmake . -G "Visual Studio 14 2015 Win64"
    -DCMAKE_INSTALL_PREFIX=C:\Projects\libs
    "-DCMAKE_BUILD_TYPE=%CONFIGURATION%" 
    "-DBOOST_ROOT=C:\Libraries\boost_1_63_0"

build:
  project: INSTALL.vcxproj

notifications:
  - provider: Email
    to:
      - demiobenour@gmail.com
